#10 Implement AutoScalingGroup, LaunchConfiguration
NaverCloudPlatform/terraform-provider-ncloud pull request #147
Opened 2021-01-21 04:29 UTC by yoogle96

## Features
### Resource
- resource_ncloud_launch_configuration
- resource_ncloud_auto_scaling_group
### Data Source
- datasource_ncloud_launch_configuration
- datasource_ncloud_auto_sclaing_group
### Test
**AutoScalingGroup**
```text
=== RUN   TestAccDataSourceNcloudAutoScalingGroup_classic_basic
=== PAUSE TestAccDataSourceNcloudAutoScalingGroup_classic_basic
=== CONT  TestAccDataSourceNcloudAutoScalingGroup_classic_basic
=== RUN   TestAccDataSourceNcloudAutoScalingGroup_vpc_basic
=== PAUSE TestAccDataSourceNcloudAutoScalingGroup_vpc_basic
=== CONT  TestAccDataSourceNcloudAutoScalingGroup_vpc_basic
--- PASS: TestAccDataSourceNcloudAutoScalingGroup_classic_basic (377.79s)
--- PASS: TestAccDataSourceNcloudAutoScalingGroup_vpc_basic (412.89s)
=== RUN   TestAccResourceNcloudAutoScalingGroup_classic_basic
=== PAUSE TestAccResourceNcloudAutoScalingGroup_classic_basic
=== CONT  TestAccResourceNcloudAutoScalingGroup_classic_basic
--- PASS: TestAccResourceNcloudAutoScalingGroup_classic_basic (394.96s)
=== RUN   TestAccResourceNcloudAutoScalingGroup_vpc_basic
=== PAUSE TestAccResourceNcloudAutoScalingGroup_vpc_basic
=== CONT  TestAccResourceNcloudAutoScalingGroup_vpc_basic
--- PASS: TestAccResourceNcloudAutoScalingGroup_vpc_basic (535.17s)
=== RUN   TestAccResourceNcloudAutoScalingGroup_classic_disappears
=== PAUSE TestAccResourceNcloudAutoScalingGroup_classic_disappears
=== CONT  TestAccResourceNcloudAutoScalingGroup_classic_disappears
--- PASS: TestAccResourceNcloudAutoScalingGroup_classic_disappears (379.78s)
=== RUN   TestAccResourceNcloudAutoScalingGroup_vpc_disappears
=== PAUSE TestAccResourceNcloudAutoScalingGroup_vpc_disappears
=== CONT  TestAccResourceNcloudAutoScalingGroup_vpc_disappears
--- PASS: TestAccResourceNcloudAutoScalingGroup_vpc_disappears (529.94s)
PASS
```

**LaunchConfiguration**
```text
=== RUN   TestAccDataSourceNcloudLaunchConfiguration_classic_basic
=== PAUSE TestAccDataSourceNcloudLaunchConfiguration_classic_basic
=== CONT  TestAccDataSourceNcloudLaunchConfiguration_classic_basic
=== RUN   TestAccDataSourceNcloudLaunchConfiguration_vpc_basic
=== PAUSE TestAccDataSourceNcloudLaunchConfiguration_vpc_basic
=== CONT  TestAccDataSourceNcloudLaunchConfiguration_vpc_basic
--- PASS: TestAccDataSourceNcloudLaunchConfiguration_vpc_basic (4.75s)
--- PASS: TestAccDataSourceNcloudLaunchConfiguration_classic_basic (6.83s)
=== RUN   TestAccResourceNcloudLaunchConfiguration_classic_basic
=== PAUSE TestAccResourceNcloudLaunchConfiguration_classic_basic
=== CONT  TestAccResourceNcloudLaunchConfiguration_classic_basic
=== RUN   TestAccResourceNcloudLaunchConfiguration_vpc_basic
=== PAUSE TestAccResourceNcloudLaunchConfiguration_vpc_basic
=== CONT  TestAccResourceNcloudLaunchConfiguration_vpc_basic
=== RUN   TestAccResourceNcloudLaunchConfiguration_classic_disappears
=== PAUSE TestAccResourceNcloudLaunchConfiguration_classic_disappears
=== CONT  TestAccResourceNcloudLaunchConfiguration_classic_disappears
=== RUN   TestAccResourceNcloudLaunchConfiguration_vpc_disappears
=== PAUSE TestAccResourceNcloudLaunchConfiguration_vpc_disappears
=== CONT  TestAccResourceNcloudLaunchConfiguration_vpc_disappears
--- PASS: TestAccResourceNcloudLaunchConfiguration_vpc_disappears (4.75s)
--- PASS: TestAccResourceNcloudLaunchConfiguration_vpc_basic (5.94s)
--- PASS: TestAccResourceNcloudLaunchConfiguration_classic_disappears (7.48s)
--- PASS: TestAccResourceNcloudLaunchConfiguration_classic_basic (8.85s)
PASS
```

2021-01-22 05:51 UTC, iDevSK commented on ncloud/resource_ncloud_auto_scaling_group.go
> +			"zone_list": {
`zone` 이란 단어가 코드로 통상 사용하고 있어서, `zone_no_list` 가 좋을 것 같습니다.

2021-01-22 05:53 UTC, iDevSK commented on ncloud/resource_ncloud_auto_scaling_group.go
> +				ValidateDiagFunc: ToDiagFunc(validation.StringLenBetween(1, 5)),
SVR(서버), LOADB(로드밸런서) Validation check 부탁 드립니다.

2021-01-22 05:56 UTC, iDevSK commented on ncloud/resource_ncloud_auto_scaling_group.go
> +			},
여기서 상태값들은, 항상 변하므로 `tfstate` 에서 관리할 필요가 없을것 같습니다. 
`server_instance_no` 값만 관리하면 될 것 같습니다.

2021-01-22 06:12 UTC, iDevSK commented on ncloud/resource_ncloud_auto_scaling_group.go
> +func getAutoScalingGroup(config *ProviderConfig, id string) ([]*AutoScalingGroup, error) {
해당 func 의 return type을 `*AutoScalingGroup` 로 해도 되지 않을까요?

2021-01-22 06:12 UTC, iDevSK commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	list := make([]*AutoScalingGroup, 0)
해당 부분을 list 로 구현하는 이유가 있을까요?

2021-01-22 06:22 UTC, sangkyu-kim requested changes

2021-01-22 06:22 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +			"zone_list": {
zone 이란 단어가 코드로 통상 사용하고 있어서, `zone_no_list` 가 좋을 것 같습니다.

2021-01-22 06:22 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +				ValidateDiagFunc: ToDiagFunc(validation.StringLenBetween(1, 5)),
SVR(서버), LOADB(로드밸런서) Validation check 부탁 드립니다.

2021-01-22 06:22 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +			},
여기서 상태값들은, 항상 변하므로 `tfstate` 에서 관리할 필요가 없을것 같습니다.
`server_instance_no` 값만 관리하면 될 것 같습니다.

2021-01-22 06:22 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	list := make([]*AutoScalingGroup, 0)
해당 부분은 list 로 처리하지말고 `*AutoScalingGroup` 로 처리하는게 어떨까요?

2021-01-22 06:22 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	return nil
```suggestion
	return resourceNcloudAutoScalingGroupRead(d, config)
```

2021-01-22 06:23 UTC, yoogle96 reviewed
.

2021-01-22 06:25 UTC, yoogle96 commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	list := make([]*AutoScalingGroup, 0)
Data Source에서 해당 함수를 사용하는데, Filter를 사용할 경우 모든 List에서 Filter 값으로 걸러주기 위함입니다.
해당 함수에서 *AutoScalingGroup만 리턴하고 Data Source에서 따로 전체를 조회하는 함수를 구현해도 될것 같습니다.

Data Source에서 Filter를 사용할 경우 Data Source에서 Read 함수를 다시 구현하는게 좋을까요?

2021-01-22 06:26 UTC, yoogle96 commented on ncloud/resource_ncloud_auto_scaling_group.go
> +			"zone_list": {
> zone 이란 단어가 코드로 통상 사용하고 있어서, `zone_no_list` 가 좋을 것 같습니다.

넵 변경하도록 하겠습니다.

2021-01-22 06:26 UTC, yoogle96 commented on ncloud/resource_ncloud_auto_scaling_group.go
> +				ValidateDiagFunc: ToDiagFunc(validation.StringLenBetween(1, 5)),
> SVR(서버), LOADB(로드밸런서) Validation check 부탁 드립니다.

넵 추가하겠습니다~

2021-01-22 06:31 UTC, yoogle96 commented on ncloud/resource_ncloud_auto_scaling_group.go
> +			},
> 여기서 상태값들은, 항상 변하므로 `tfstate` 에서 관리할 필요가 없을것 같습니다.
> `server_instance_no` 값만 관리하면 될 것 같습니다.

넵 `server_instance_no`만 관리하도록 변경하겠습니다.

2021-01-22 06:38 UTC, yoogle96 commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	return nil
감사합니다! 👍

2021-01-22 07:22 UTC, sangkyu-kim commented on ncloud/resource_ncloud_launch_configuration.go
> +			"region": {
해당값은 지워주셔도 될 것 같습니다.

2021-01-22 07:22 UTC, sangkyu-kim commented on ncloud/resource_ncloud_launch_configuration.go
> +			"status": {
해당값은 지워주셔도 될 것 같습니다.

2021-01-26 04:10 UTC, sangkyu-kim requested changes

2021-01-26 04:10 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +				if errBody.ReturnCode == "50160" || errBody.ReturnCode == "50150" {
여기 코드는 상수 처리하면 추후에 코드 읽을때 더 도움될것 같습니다.

2021-01-26 04:10 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +				if errBody.ReturnCode == "1250700" {
여기도 상수 처리 부탁 드립니다.

2021-01-26 04:10 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	return resource.Retry(DefaultCreateTimeout, func() *resource.RetryError {
해당 Autoscailing 은 DesireCapacity 에 따라 사용자쪽에서 Timeout 을 조절할 필요도 있을것 같은데요, Schema 에서 받을 수 있게 하면 더 좋을것 같습니다. (ncloud_server 참조)
```go
Timeouts: &schema.ResourceTimeout{
	Create: schema.DefaultTimeout(DefaultCreateTimeout),
	Delete: schema.DefaultTimeout(DefaultTimeout),
},
```

2021-01-26 04:10 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +			"server_instance_list": {
타 상품과 통일성을 위해 `server_instance_no_list` 가 좋을것 같습니다.

2021-01-26 04:10 UTC, sangkyu-kim commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	reqParams := &vautoscaling.CreateAutoScalingGroupRequest{
아래 파라미터에서, Mandatory 한 파라미터들은 아래와 같이 바꾸어서
nil 일 경우 오류나게 하는것이 괜찮을것 같습니다. 다른 Request들도 확인 부탁 드립니다.

#### AS-IS
```go
StringPtrOrNil(d.GetOk("launch_configuration_no"))
```

#### TO-BE
```go
ncloud.String(d.Get("launch_configuration_no").(string))
```

2021-01-26 04:13 UTC, sangkyu-kim commented on ncloud/resource_ncloud_launch_configuration.go
> +			"access_control_group_configuration_no_list": {
API 는 위에가 맞는데,  다른 상품들도 아래와 같이 바꾸어서 명칭 변경 부탁 드릴게요
 `access_control_group_no_list`

2021-01-26 10:10 UTC, yoogle96 commented on ncloud/resource_ncloud_auto_scaling_group.go
> +	return resource.Retry(DefaultCreateTimeout, func() *resource.RetryError {
스키마에 `wait_for_capacity_timeout` 속성을 추가하여 Default 값을 10분으로 설정하였습니다.
사용자가 `wait_for_capacity_timeout = "{N}m"` 등의 형식으로 Capacity Timeout을 조절할 수 있도록 하였습니다.

2021-01-28 08:53 UTC, sangkyu-kim approved these changes

2021-01-28 10:40 UTC, merged

2021-01-28 10:50 UTC, sangkyu-kim commented
👍