[WIP] #151 Support vpc load balancer
NaverCloudPlatform/terraform-provider-ncloud pull request #152
Opened 2021-02-23 01:25 UTC by yoogle96

## Description
solve #151 

## Features

### Resource
- resource_ncloud_lb
- resource_ncloud_lb_target_group
- resource_ncloud_lb_target_group_attachment

2021-02-23 04:49 UTC, sangkyu-kim requested changes

2021-02-23 04:49 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +				Optional: true,
여기 `Optional` 는 없어야 될 것 같습니다.

2021-02-23 04:49 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +			},
해당 `target_no_list` 는 `ncloud_lb_target_gruop_attachment` 와 중복되는 기능이라, 지워주셔도 될 것 같습니다.

2021-02-23 04:49 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +			},
여기에 `ForceNew` 가 추가 되어야 할 것 같네요

2021-02-23 04:59 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group.go
> +				Optional: true,
아하 넵 반영하였습니다!

2021-02-23 05:08 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +	return resourceNcloudTargetGroupRead(d, meta)
use_sticky_session, use_proxy_protocol  관련 로직을 위해 아래와 같이 변경 되어야 할 것 같습니다.

```suggestion
	return resourceNcloudTargetGroupUpdate(d, meta)
```

2021-02-23 05:09 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +	}
해당 부분에서는 수정 여부와 상관없이 매번 호출되는데, hasChange 등의 변경 여부 검사가 필요 해 보이네요

2021-02-23 05:13 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group_attachment.go
> +				return nil
혹시 해당 로직 설명 해 주실수 있을까요?
`HealthCheckStatus` 는 서버의 Application 상태에 따라 `UP` 되거나  `DOWN` 되는건데
`DOWN` 되면 리소스를 지우는것으로 보여서요.

2021-02-23 05:32 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group.go
> +			},
`Optional` 속성만 지워주고 Read 용도로만 사용하는건 어떨까요? `ncloud_lb_target_gruop_attachment` 에서는 Target Group에 속한 Target 들에 대한 모든 리스트를 볼 수 있는 기능이 없어서요

2021-02-23 06:08 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group.go
> +			},
넵 추가하였습니다! 감사합니다~

2021-02-23 06:09 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group.go
> +	return resourceNcloudTargetGroupRead(d, meta)
네 반영하였습니다!

2021-02-23 06:14 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group.go
> +	}
넵 해당 API 요청하려면 어차피 기존에 변경되지 않은 값도 함께 요청 보내야해서 hasChange를 넣지 않았는데, 해당 API의 요청 파라미터 `use_sticky_session`, `use_proxy_protocol`, `algorithm_type` 중 하나라도 변경 사항 있을시만 요청하도록 수정하였습니다.

2021-02-23 06:16 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +			},
네 `Computed` 로 만 해주세요

2021-02-23 06:16 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group_attachment.go
> +				return nil
앗.. 이건 제 실수 같네요 제가 `HealthCheckStatus` 속성을 잘못 이해하고 있었습니다. 해당 부분 제거하고 Target이 존재하는지 여부만 확인하도록 수정하였습니다. Ex ) 서버 인스턴스가 삭제된 경우

2021-02-25 10:31 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb.go
> +	})
아래애서 Sort를 한번 더 해주는것 같은데, 여길 지우면 어떻게 되나요?

2021-02-25 10:51 UTC, yoogle96 commented on ncloud/resource_ncloud_lb.go
> +	})
넵 이 부분 테스트하다가 들어간거라서 중복 로직이라 제거할 예정입니다.

2021-03-26 08:28 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_listener.go
> +	}
해당 부분은 별도 메소드로 뺴면, test 코드 data_* 등에서 중복된 코드가 감소 될것 같은데요 어떠신지요?

2021-03-26 08:44 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_listener.go
> +	reqParams := &vloadbalancer.ChangeLoadBalancerListenerConfigurationRequest{
다른 속성들이 ForceNew 라서 문제가 없긴 한데
`d.HasChanges("port", "protocol", "ssl_certificate_no", "use_http2", "tls_min_version_type")` 을 추가하면 추후에 다른 속성이 추가 될때, 불필요하게 호출되는 부분을 줄일 수 있을 것 같습니다.

2021-03-26 08:50 UTC, sangkyu-kim commented on ncloud/data_source_ncloud_lb.go
> +		},
요 속성이 왜 따로 나와있는건지 알 수 있을까요? `GetSingularDataSourceItemSchemaContext` 에서 처리 될 것 같아서요.

2021-03-26 08:50 UTC, sangkyu-kim commented on ncloud/data_source_ncloud_lb_listener.go
> +		},
이 두 속성도 따로 빼놓은 이유가 궁금합니다.

2021-03-26 08:55 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +				ForceNew: true,
요건 삭제 부탁 드릴게요.

2021-03-26 09:00 UTC, yoogle96 commented on ncloud/data_source_ncloud_lb.go
> +		},
현재 `GetSingularDataSourceItemSchemaContext` 함수에서는 필드가 `Required`이거나 `Computed`일 경우에만 스키마로 적용을 하는데요, 해당 속성들은 `Optional` 속성만 갖고 있어서 그렇습니다.
https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/5c8f0746cdabe05678427b16fc795dc94138a1b9/ncloud/helpers.go#L90-L122

`convertResourceFieldsToDatasourceFields` 해당 함수에서 `Required`이거나 `Computed`일 경우에만 Datasource 스키마로 적용되는 이유가 있을까요? 함부로 수정하면 다른 리소스들에 영향이 있을까봐 그대로 두고 임시로 Datasource에 속성을 추가해놓는 방식으로 해두었습니다.

2021-03-26 09:03 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group.go
> +				ForceNew: true,
https://github.com/NaverCloudPlatform/terraform-provider-ncloud/pull/152#discussion_r580791051
요기서 `Computed` 속성만 해놓기로 하였는데, 삭제하는게 맞을까용?

2021-03-26 09:04 UTC, sangkyu-kim commented on ncloud/data_source_ncloud_lb.go
> +		},
네 확인했습니다 ^^

2021-03-26 09:06 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_listener.go
> +	reqParams := &vloadbalancer.ChangeLoadBalancerListenerConfigurationRequest{
감사합니다 말씀해주신 부분 반영하겠습니다~

2021-03-26 09:07 UTC, sangkyu-kim commented on ncloud/resource_ncloud_lb_target_group.go
> +				ForceNew: true,
아 `ForceNew` 속성을 말씀드린거였습니다.

2021-03-26 09:09 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_target_group.go
> +				ForceNew: true,
아아 네 `ForceNew` 속성은 제거해야겠네여 감사합니다!

2021-03-29 09:46 UTC, yoogle96 commented on ncloud/resource_ncloud_lb_listener.go
> +	}
메소드로 빼서 중복 코드 제거 완료하였습니다~

2021-03-29 09:53 UTC, sangkyu-kim approved these changes
👍 LGTM

2021-03-30 05:44 UTC, merged