feat: Add mssql resource
NaverCloudPlatform/terraform-provider-ncloud pull request #369
Opened 2023-09-04 08:41 UTC by sososo0

**Related issues**
#283

**PR Summary**
Add mssql resource, data source, tests, guide docs

**PR Detail Descriptions**

1. cloud_mssql.go
- function of Create, Read, Delete

2. cloud_mssql_test.go
- tested basic with default options

3. cloud_mssql_data_source.go
- got 'instanceList' through "getcloudmssqlinstancelist" to support filtering

4. cloud_mssql_data_source_test.go
- tested basic

5. mssql.md 
- data source
- resource

2023-09-12 08:55 UTC, youngmn reviewed
docs 디렉토리에 들어갈 mssql 의 resource, data-source 가이드 문서도 작성 가능할까요?

2023-09-12 09:14 UTC, sososo0 commented
아 넵! 해보겠습니다!

2023-09-23 08:37 UTC, sososo0 commented
요청하신 부분 반영해서 pr 올렸습니다! 
- mssql 가이드 문서 작성했습니다. 

추가적으로 data source code에서 mssql instance를 잘 가져오지 못하는 오류를 발견해, 해당 부분 수정하였습니다.

2023-09-24 12:28 UTC, yoogledev commented on internal/service/cloudmssql/cloud_mssql.go
> +			"config_group_no": {
`mirror_subnet_no` 속성은 스키마에 정의만 되어 있고, 요청 파라미터에 포함되어있지는 않는것 같습니다. https://api.ncloud-docs.com/docs/database-vmssql-createcloudmssqlinstance 가이드의 `mirrorSubnetNo` 스펙 참고하여서 멀티존 여부 `isMultiZone`에 따라서 요청 파라미터에 추가하면 좋을것 같습니다~

2023-09-24 12:28 UTC, yoogle96 commented on internal/service/cloudmssql/cloud_mssql.go
> +			},
https://github.com/NaverCloudPlatform/terraform-provider-ncloud/blob/c95c2272c95d60e817a0f7f74d76d0f22d07104d/internal/service/autoscaling/auto_scaling_group.go#L73

위와 같이 입력 받을수 있는 옵션을 스키마에서 검증할 수 있습니다. 현재 스펙상 `HDD`, `SSD` 두개의 옵션을 받을 수 있는데 위 코드 참고하여서 수정해주세요~!

2023-09-24 12:28 UTC, yoogle96 commented on internal/service/cloudmssql/cloud_mssql.go
> +				)),
과거 `ValidateFunc` -> `ValidateDiagFunc` 으로 변환해주는 helper가 sdk에서 제공되지 않았던 상태였었어서 저희 내부에 변환해주는 코드를 카피해서 사용했었는데요, 해당 함수가 2.4.0[#ref](https://github.com/hashicorp/terraform-plugin-sdk/issues/534) 버전 부터  SDK에 추가되었습니다. 아래와 같이 sdk 버전으로 사용하면 좋을것 같습니다~ 추후 다른 리소스들에서도 리펙토링 대상이겠네요!

```suggestion
				ValidateDiagFunc: validation.ToDiagFunc(validation.All(
					validation.StringLenBetween(3, 15),
					validation.StringMatch(regexp.MustCompile(`^[a-zA-Z0-9\-가-힣]+$`), "Composed of alphabets, numbers, korean, hyphen (-)."),
				)),
```

2023-09-24 12:28 UTC, yoogle96 commented on internal/service/cloudmssql/cloud_mssql.go
> +					validation.IntBetween(10000, 20000),
`1433` 도 허용해줘야할 것 같습니다~

2023-09-24 12:31 UTC, sososo0 commented
넵! 반영해서 수정하고 다시 pr 보내겠습니다!

2023-10-05 16:51 UTC, sososo0 commented
pr 다시 보냈습니다! 수정사항은 다음과 같습니다.
- is_multi_zone의 값에 따른 mirror_subnet_no 값 추가했습니다. 
- ssd, hdd 두 개의 입력 옵션 검증 추가했습니다.
- ValidateDiagFunc 관련해서 sdk 변경사항 반영해서 validation 관련 수정했습니다. 다른 리소스들도 추가로 같이 수정했습니다.
- 1433 포트 추가했습니다.
- resource mssql 가이드 문서 중에서 attirbute에 mirror_subnet_no 추가했습니다.

2023-10-12 08:43 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql.go
> +			},
provider config로 설정된 region 값을 사용하고, region_code attribute는 사용되지 않으므로 삭제해도 좋겠습니다.

2023-10-12 08:43 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql.go
> +					validation.IntDivisibleBy(1433),
`IntDivisibleBy(1433)`은 1433 포트 외 2866 등 1433의 배수에 해당하는 포트도 허용되므로 IntBetween(1433, 1433) 이나 IntInSlice([]int{ 1433}) 또는 validation 함수를 추가하는 형태로 변경해주시면 좋겠습니다.

2023-10-12 08:43 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql_data_source.go
> +			ForceNew: true,
data source는 리소스의 값을 얻어오는 용도로 사용하고 값을 사용자가 직접 변경하지 않기 때문에 `ForceNew` 가 사용되지 않는 것이 일반적이니,`id` attribute와 다른 attribute에 정의된 `ForceNew` 설정을 생략해도 좋겠습니다.

2023-10-12 08:43 UTC, wonchulee commented on internal/service/cloudmssql/types.go
> +	AccessControlGroupNoList     []*string `json:"accessControlGroupNoList,omitempty"`
mssql resource와 data source의 attribute들이 `"service_name"` 와 같이 snake case로 네이밍되어 있어서, json tag 또한 snake case로 구성되어야 할 것으로 보입니다. 값을 가져오는 동작에 문제가 없는지 한 번 확인부탁드립니다.

2023-10-13 09:59 UTC, wonchulee commented
just rebased on top of latest main branch

2023-10-13 10:46 UTC, sososo0 commented
넵! 리뷰 반영해서 pr 다시 올리겠습니다.

2023-10-16 04:54 UTC, youngmn commented on internal/service/cloudmssql/cloud_mssql.go
> +				ValidateDiagFunc: ToDiagFunc(validation.IntBetween(1, 30)),
여기도 변경이 필요하네요
ToDiagFunc -> validation.ToDiagFunc

2023-10-25 02:10 UTC, yoogle96 commented on internal/service/cloudmssql/cloud_mssql_data_source.go
> +		"backup_time": {
read 요청시 필요한 파라미터들은 Optional 속성이 있어야 하는게 맞는데, 그 외 필드들에 Optional이 있는 이유가 있을까용?? ForceNew도 지워도 될 것 같습니다!!

2023-10-25 02:11 UTC, yoogle96 approved these changes
수고하셨습니다~ 👍👍👍👍
`mirror_subnet_no`가 아직 SDK에 반영되지 않아서, 이거는 추후 SDK에 반영되면 생성 요청에 추가하면 될 것 같습니다!!

2023-10-29 01:02 UTC, sososo0 commented
comment 반영해서 새로 pr 올렸습니다! 
원철 멘토님께서 달아주신 comment 중에서 types.go에서 camel case를 snake case로 변경하는 것은 snake case로 변경하고 test를 진행하였을 때 다음과 같은 panic이 발생하는 것을 보았습니다!  

```
panic: interface conversion: interface {} is nil, not string
```

따라서, 이 부분에 대해서는 camel case를 유지하였습니다. 나머지 comment들은 모두 반영하고 그에 따라서 test가 잘 통과하는 것까지 확인하였습니다!

2023-10-29 01:05 UTC, sososo0 commented
의선 멘토님께서 approve 해주셔서 merge 하겠습니다!! 
그동안 같이 개발할 수 있어서 즐겁고 감사했습니다 😄

2023-10-30 01:21 UTC, wonchulee requested changes
사소한 것이지만 폴더 및 파일 명도 `cloud_mssql -> mssql`로 함께 변경하면 더 좋겠습니다!

2023-10-30 01:21 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql.go
> +			},
Sensitive 속성을 함께 추가해주시면 좋겠습니다. 그리고 패스워드 validation 조건에 backtick이 빠진 것으로 보입니다, regex를 수정할 때, 동일한 작업을 단순하게 수정한 내용을 참고하셔도 좋겠습니다. https://github.com/dusdjhyeon/terraform-provider-ncloud/commit/ba1a9bd694b1e6fe5b2381239c87e5bf809f4583

2023-10-30 01:21 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql_data_source.go
> +		CloudMssqlServerName:  StringPtrOrNil(d.GetOk("server_name")),
`server_name` attribute가 mssql datesource 에 존재하지 않습니다. 해당값을 사용하려면 `server_name` attribute를 optional | computed 로 추가가 필요해 보입니다.

2023-10-30 01:21 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql_data_source.go
> +		SubnetNo:              StringPtrOrNil(d.GetOk("subnet_no")),
마찬가지로 zone_code, vpc_no, subnet_no attribute가 mssql datasource에 존재하지 않으므로 유효하지 않은 코드입니다. 각각의 attribute를 추가할 필요가 있습니다.

2023-10-30 01:21 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql_data_source_test.go
> +			is_ha = ncloud_mssql.mssql.is_ha
is_ha는 computed 특성만 가진 attribute가 되어야하므로, 사용자가 입력할 수 없는 argument로 config에서 제외하는 것이 맞을 것 같습니다.

2023-10-30 01:21 UTC, wonchulee commented on internal/service/cloudmssql/cloud_mssql_data_source.go
> +		},
`is_ha`, `is_multi_zone`, `is_backup`, `backup_file_retention_period`, `backup_time`, `port`, `image_product_code`, `instance_no`, `server_instance_list` attribute는 모두 사용자가 입력한 값을 사용하지 않고, `GetCloudMssqlInstanceList()`의 결과로 가져오는 값이기 때문에 Optional behavior 가 제외되어야 합니다.

그리고 `instance_no`는 `id`와 동일한 역할로 사용되고 있으니, `id` 이름으로 사용하는 것이 좋을 것 같습니다.

2023-10-30 01:21 UTC, wonchulee commented on docs/data-sources/mssql.md
> +* `is_backup` - Whether using backup of the specific MSSQL to retrieve.
engine_version 은 존재하지 않는 항목으로 삭제 부탁드립니다.
is_ha, is_multi_zone, is_backup은 Computed 속성만을 가지므로(Optional인 것은 Computed로 수정필요) argument가 아닌 아래 Attributes reference 항목에 추가 부탁드립니다.

2023-10-31 10:29 UTC, sososo0 commented
comment들 반영했습니다! 
추가적으로 data_source에 대한 attirbute들 수정 내용에 따라 data_source_test.go의 내용도 같이 수정해주었습니다.
test 해보았을 때 잘 통과되는 것 까지 확인했습니다.

2023-11-01 11:59 UTC, wonchulee reviewed
한번에 리뷰했어야 했는데, 몇가지 놓친 부분들이 있었네요, 번거롭더라도 몇가지 코멘트 추가했으니 확인 부탁드립니다.

2023-11-01 11:59 UTC, wonchulee commented on docs/resources/mssql.md
> +* `is_ha` - (Optional) Whether is High Availability or not. If High Availability is selected, 2 servers including the Standby Master server will be created and additional charges will be incurred. De
is_ha가 ax Optional로 잘못 표기된 것 같아보입니다. -> (Required)

2023-11-01 11:59 UTC, wonchulee commented on docs/resources/mssql.md
> +* `engine_version_code` - (Optional) Engine version code to determine the mssql engine specification to create. It can be obtained through the `data.(s)` action. Default : Selected as the latest vers
engine_version_code는 존재하지 않는 argument이므로 삭제 부탁드립니다.

2023-11-01 11:59 UTC, wonchulee commented on internal/service/mssql/mssql.go
> +			time.Sleep(3 * time.Minute)
waitForCloudMssqlDeletion()에서 mysql instance 의 상태 값으로 삭제가 완료되었음을 판단하여 Sleep을 사용하지 않도록 변경이 필요해보입니다. mssql API의 개선이 필요한 부분인데, 해당 API의 개선사항이 아직 배포되지 않았다면, 배포 일정을 확인해보겠습니다.

2023-11-02 07:14 UTC, sososo0 commented on internal/service/mssql/mssql.go
> +			time.Sleep(3 * time.Minute)
해당 코드를 주석 상태로 변경하고 test를 하면 
```
error=
  | exit status 1
  |
  | Error: error waiting for Cloud Mssql instance (20348462) to become terminating: Status: 400 Bad Request, Body: {
  |   "responseError": {
  |     "returnCode": "5001269",
  |     "returnMessage": "It's a cluster deleted."
  |   }
  | }
  |
```

2023-11-02 13:14 UTC, wonchulee commented on internal/service/mssql/mssql.go
> +			time.Sleep(3 * time.Minute)
그렇군요, 관련 API를 확인해보고 말씀드리겠습니다.

2023-11-04 02:28 UTC, sososo0 commented
waitForCloudMssqlDeletion() comment 만 제외하고 나머지 2개의 comment에 대해서는 pr 올렸습니다!

2023-11-06 07:54 UTC, wonchulee commented on internal/service/mssql/mssql.go
> +			time.Sleep(3 * time.Minute)
@sososo0, 현 상태에서 리소스 삭제 테스트시 에러 대신 상태 값이 정상 반환되는 것으로 보입니다. 다시 한 번 확인부탁드릴 수 있을까요?

2023-11-07 05:31 UTC, wonchulee commented on internal/service/mssql/mssql.go
> +			time.Sleep(3 * time.Minute)
해당 API 개선이 필요한 것으로 확인되어, 개선 후 Sleep을 제거하고 반영할 예정입니다.

2023-11-24 13:59 UTC, wonchulee commented on internal/service/mssql/mssql.go
> +			time.Sleep(3 * time.Minute)
개선사항 배포되어 문제 해결된 것 확인했습니다.

2023-11-24 14:51 UTC, wonchulee approved these changes
LGTM 👍 
main 브랜치로 리베이스 하는 과정에서 컨플릭이 너무 많이 발생해, 기존 커밋들을 하나로 스쿼시했습니다. (다음번 작업하실때 컨플릭 발생시 merge 대신 rebase로 정리하시면 추후 작업이 편리합니다)

2023-11-24 14:59 UTC, merged