#16 subnet management
NaverCloudPlatform/terraform-provider-ncloud pull request #39
Opened 2020-07-27 03:40 UTC by sangkyu-kim

resolve #16

2020-07-27 09:03 UTC, YuSungDuk requested changes

2020-07-27 09:03 UTC, YuSungDuk commented on ncloud/data_source_ncloud_subnet.go
> +				Required: true,
Please add "Description"

2020-07-27 09:03 UTC, YuSungDuk commented on ncloud/data_source_ncloud_subnets.go
> +				ValidateFunc: validation.StringInSlice([]string{"GEN", "LOADB"}, false),
Please check "BM"
![image](https://user-images.githubusercontent.com/34295380/88519902-d2fb1f00-d02d-11ea-8811-89bc06ed8f5e.png)

2020-07-27 09:03 UTC, YuSungDuk commented on ncloud/data_source_ncloud_subnet_test.go
> +	cidr := fmt.Sprintf("10.2.2.0/24")
remove `fmt.Sprintf`

2020-07-27 09:03 UTC, YuSungDuk commented on ncloud/data_source_ncloud_subnet_test.go
> +	name := fmt.Sprintf("testacc-data-subnet-basic")
remove `fmt.Sprintf`

2020-07-27 09:34 UTC, YuSungDuk requested changes

2020-07-27 09:34 UTC, YuSungDuk commented on ncloud/resource_ncloud_subnet.go
> +					validation.StringMatch(regexp.MustCompile(`^[A-Za-z0-9-*]+$`), "Composed of alphabets, numbers, hyphen (-) and wild card (*)."),
![image](https://user-images.githubusercontent.com/34295380/88526777-553c1100-d037-11ea-9123-3cb03bb27016.png)
`-` or `*` 으로도 시작하는 걸 허용하는 정규표현식 같습니다. `server` 상품도 마찬가지네요..

2020-07-27 09:34 UTC, YuSungDuk commented on ncloud/resource_ncloud_subnet.go
> +					validation.StringMatch(regexp.MustCompile(`^[A-Za-z0-9-*]+$`), "Composed of alphabets, numbers, hyphen (-) and wild card (*)."),
`*` 이 허용되는게 맞는 건가요?

2020-07-27 09:40 UTC, sangkyu-kim commented on ncloud/resource_ncloud_subnet.go
> +					validation.StringMatch(regexp.MustCompile(`^[A-Za-z0-9-*]+$`), "Composed of alphabets, numbers, hyphen (-) and wild card (*)."),
@YuSungDuk 서버 Validation을 그대로 사용했는데, 서버도 허용되지 않아야 할것 같네요, 변경 했습니다.

2020-07-27 12:41 UTC, YuSungDuk commented on ncloud/resource_ncloud_subnet.go
> +				Description:  "Internet Gateway Only. PUBLC(Yes/Public), PRIVATE(No/Private).",
```suggestion
				Description:  "Internet Gateway Only. PUBLIC(Yes/Public), PRIVATE(No/Private).",
```

2020-07-27 12:44 UTC, YuSungDuk requested changes

2020-07-27 12:44 UTC, YuSungDuk commented on ncloud/validators.go
> +	if !regexp.MustCompile(`^[A-Za-z0-9-]+$`).MatchString(value) {
![image](https://user-images.githubusercontent.com/34295380/88542782-f1731180-d051-11ea-9002-c022fa0e4e46.png)

2020-07-27 12:44 UTC, YuSungDuk commented on ncloud/validators.go
> +func validateInstanceName(v interface{}, k string) (ws []string, errors []error) {
`validateInstanceName` 테스트 코드도 추가해 주세요

2020-07-27 12:44 UTC, YuSungDuk commented on ncloud/resource_ncloud_subnet_test.go
> +	cidr := fmt.Sprintf("10.2.2.0/24")
```suggestion
	cidr := "10.2.2.0/24"
```
`fmt.Sprintf` 를 제거해도 되지 않나요?

2020-07-27 12:44 UTC, YuSungDuk commented on ncloud/data_source_ncloud_subnets_test.go
> +	return fmt.Sprint(`
`fmt.Sprintf` 를 제거해도 되지 않나요?

2020-07-27 12:44 UTC, YuSungDuk commented on ncloud/data_source_ncloud_subnet_test.go
> +	cidr := fmt.Sprint("10.2.2.0/24")
`fmt.Sprint` 를 제거해도 되지 않나요?

2020-07-27 12:45 UTC, YuSungDuk requested changes

2020-07-27 12:45 UTC, YuSungDuk commented on ncloud/validators.go
> +
처음과 끝외에 소문자, 숫자 , "-" 만 허용을 체크하는 정규 표현식도 추가해 주세요

2020-07-28 02:05 UTC, sangkyu-kim commented on ncloud/validators.go
> +
@YuSungDuk vpc mc fe 와 동일한 validation 추가 하였습니다.

2020-07-28 02:32 UTC, YuSungDuk requested changes

2020-07-28 02:32 UTC, YuSungDuk commented on ncloud/resource_ncloud_subnet.go
> +				Required:     true,
![image](https://user-images.githubusercontent.com/34295380/88611173-6fbbcc00-d0c3-11ea-8dd4-764a2e852c08.png)
```suggestion
				Optional:     true,
```

2020-07-28 02:40 UTC, sangkyu-kim commented
retest this please

2020-07-28 02:43 UTC, YuSungDuk requested changes

2020-07-28 02:43 UTC, YuSungDuk commented on ncloud/resource_ncloud_subnet.go
> +		Refresh:    NetworkACLStateRefreshFunc(client, d.Get("network_acl_no").(string)),
`NetworkACLStateRefreshFunc` 정의되어있지 않은듯 합니다.

2020-07-28 02:46 UTC, sangkyu-kim commented on ncloud/resource_ncloud_subnet.go
> +		Refresh:    NetworkACLStateRefreshFunc(client, d.Get("network_acl_no").(string)),
다음 Network ACL 과 같이 올릴 코드였는데요, 삭제 하였습니다.

2020-07-28 02:47 UTC, YuSungDuk requested changes
대기탈 필요 없는 건가요?

2020-07-28 02:48 UTC, YuSungDuk commented on ncloud/resource_ncloud_subnet.go
> +		Refresh:    NetworkACLStateRefreshFunc(client, d.Get("network_acl_no").(string)),
이해하였습니다.

2020-07-28 02:48 UTC, YuSungDuk approved these changes
👍

2020-07-28 02:52 UTC, sangkyu-kim commented
> 👍

리뷰 하느라

2020-07-28 02:54 UTC, merged