implement route table
NaverCloudPlatform/terraform-provider-ncloud pull request #50
Opened 2020-08-06 05:59 UTC by sangkyu-kim

## Features
### Resource
- resource_ncloud_route_table
- resource_ncloud_route
- resource_ncloud_route_table_association

### Data Source
- data_source_ncloud_route_table
- data_source_ncloud_route_tables

resolve #22

2020-08-06 11:39 UTC, YuSungDuk requested changes

2020-08-06 11:39 UTC, YuSungDuk commented on ncloud/data_source_ncloud_route_table.go
> +	reqParams := &vpc.GetRouteTableListRequest{
`GetRouteTableDetailRequest` 을 안 사용한 이유가 있나요? 단건이 아닌 리스트를 사용한 이유가 있을까요?

2020-08-06 11:39 UTC, YuSungDuk commented on ncloud/data_source_ncloud_route_table.go
> +	d.Set("is_default", instance.IsDefault)
Type 이 다른 듯 합니다. String / Bool

2020-08-06 12:02 UTC, sangkyu-kim commented on ncloud/data_source_ncloud_route_table.go
> +	reqParams := &vpc.GetRouteTableListRequest{
타사 사례를 보니 `RouteTableNo` 외에 다른 검색 조건 (`VpcNo`, `Name`) 등 으로 검색하여 데이터를 가져오는데,
`GetRouteTableDetailRequest ` 의 경우는 `RouteTableNo` 로만 조회할 수 있어 `GetRouteTableListRequest` 로 구현하였습니다.

2020-08-06 12:03 UTC, sangkyu-kim commented on ncloud/data_source_ncloud_route_table.go
> +	d.Set("is_default", instance.IsDefault)
네, `is_default`의 경우 filter 조건으로 `null` 값을 허용해야 하는데, TypeBool 의 경우  `null` 을 허용하지 않아 TypeString 으로 구현하였습니다.

2020-08-07 02:56 UTC, YuSungDuk commented on ncloud/data_source_ncloud_route_table.go
> +	reqParams := &vpc.GetRouteTableListRequest{
네. 어떤 의도인지 알겠습니다.
- filter 기능을 두는 것은 어떨까요? https://www.terraform.io/docs/providers/oci/guides/filters.html
  우리가 filter 기능 사용하는 것은 없는데, 이 용도로 괜찮을 듯 합니다. OCI 에서 잘 사용하고 있네요. https://github.com/terraform-providers/terraform-provider-oci

2020-08-07 02:59 UTC, YuSungDuk commented on ncloud/data_source_ncloud_route_table.go
> +	d.Set("is_default", instance.IsDefault)
- `is_default` 는 response type 그대로, bool 을 사용하고 , filter 기능을 사용하는 것은 어떨까요? filter 도 string 밖에 지원안하긴 하지만, filter 구현이 custom 이라서 지금처럼 형변환해서 비교할 수 있을 듯 합니다.

2020-08-07 03:01 UTC, YuSungDuk requested changes
`data_source_ncloud_route_table` 와 `data_source_ncloud_route_tables` 둘다 `GetRouteTableList` 을 사용하여 중복코드 부분을 리팩토링 하는 것은 어떨까요?

2020-08-18 11:43 UTC, YuSungDuk requested changes
```
=== RUN   TestAccresourceNcloudRoute_basic
--- FAIL: TestAccresourceNcloudRoute_basic (56.91s)
    testing.go:684: Step 0 error: After applying this step, the plan was not empty:
        
        DIFF:
        
        DESTROY/CREATE: ncloud_nat_gateway.nat_gateway
          description:    "" => ""
          id:             "4964712" => "<computed>"
          name:           "ng174015f69b0" => "<computed>"
          nat_gateway_no: "4964712" => "<computed>"
          public_ip:      "110.165.20.107" => "<computed>"
          status:         "RUN" => "<computed>"
          vpc_no:         "" => "978" (forces new resource)
          zone:           "KR-1" => "KR-1"
        DESTROY/CREATE: ncloud_route.foo
          destination_cidr_block: "0.0.0.0/0" => "0.0.0.0/0"
          id:                     "route-1703446905" => "<computed>"
          is_default:             "false" => "<computed>"
          route_table_no:         "1147" => "1147"
          target_name:            "ng174015f69b0" => "<computed>"
          target_no:              "4964712" => "<computed>" (forces new resource)
          target_type:            "NATGW" => "NATGW"
          vpc_no:                 "978" => "<computed>"
        
        
        
        STATE:
        
        ncloud_nat_gateway.nat_gateway:
          ID = 4964712
          provider = provider.ncloud
          description = 
          name = ng174015f69b0
          nat_gateway_no = 4964712
          public_ip = 110.165.20.107
          status = RUN
          vpc_no = 
          zone = KR-1
        
          Dependencies:
            ncloud_vpc.vpc
        ncloud_route.foo:
          ID = route-1703446905
          provider = provider.ncloud
          destination_cidr_block = 0.0.0.0/0
          is_default = false
          route_table_no = 1147
          target_name = ng174015f69b0
          target_no = 4964712
          target_type = NATGW
          vpc_no = 978
        
          Dependencies:
            ncloud_nat_gateway.nat_gateway
            ncloud_route_table.route_table
        ncloud_route_table.route_table:
          ID = 1147
          provider = provider.ncloud
          description = for test
          is_default = false
          name = test-route-basic-ktw06
          route_table_no = 1147
          status = RUN
          supported_subnet_type = PRIVATE
          vpc_no = 978
        
          Dependencies:
            ncloud_vpc.vpc
        ncloud_vpc.vpc:
          ID = 978
          provider = provider.ncloud
          default_network_acl_no = 1059
          ipv4_cidr_block = 10.3.0.0/16
          name = test-route-basic-ktw06
          status = RUN
          vpc_no = 978
FAIL
FAIL    github.com/terraform-providers/terraform-provider-ncloud/ncloud 58.022s
FAIL
```

2020-08-18 12:42 UTC, sangkyu-kim commented
@YuSungDuk test 가 real 환경에서 진행된것 같습니다.

2020-08-18 13:53 UTC, YuSungDuk approved these changes
베타에서 확인하였습니다.

2020-08-18 13:53 UTC, merged