#32 network interface
NaverCloudPlatform/terraform-provider-ncloud pull request #66
Opened 2020-08-27 08:38 UTC by sangkyu-kim

resolve #32

2020-08-27 08:48 UTC, sangkyu-kim commented
retest this please

2020-08-28 05:11 UTC, YuSungDuk requested changes

2020-08-28 05:11 UTC, YuSungDuk commented on ncloud/resource_ncloud_network_interface.go
> +	return nil, NotSupportClassic("Network Interface")
위 `waitForVpcNetworkInterfaceAttachment` 에서 VPC 함수를 호출할 수 있으니, L194 else 문으로 옮기는 것이 좋을 듯 합니다.

2020-08-28 09:44 UTC, sangkyu-kim commented on ncloud/resource_ncloud_network_interface.go
> +	return nil, NotSupportClassic("Network Interface")
네 그게 좋겠네요, 확인 감사합니다.

2020-08-28 09:58 UTC, YuSungDuk approved these changes
👍

2020-08-28 09:59 UTC, merged