#26 vpc server
NaverCloudPlatform/terraform-provider-ncloud pull request #76
Opened 2020-09-07 12:47 UTC by sangkyu-kim

refer #26 

#### Resource
- resource_ncloud_server (Modify)

2020-09-08 13:11 UTC, sangkyu-kim commented
retest this please

2020-09-09 11:24 UTC, YuSungDuk requested changes

2020-09-09 11:24 UTC, YuSungDuk commented on ncloud/helpers.go
> +			log.Printf("[DEBUG] SetSingularResourceDataFromMapSchema >> [%s] is nil", k)
남기지 않거나 `TRACE` 레벨로 낮춰도 좋을 듯 합니다.

2020-09-09 11:24 UTC, YuSungDuk commented on ncloud/resource_ncloud_server.go
> +		BaseBlockStorageDiskDetailType: flattenMapByKey(r.BaseBlockStroageDiskDetailType, "code"),
```suggestion
		BaseBlockStorageDiskDetailType: flattenMapByKey(r.BaseBlockStorageDiskDetailType, "code"),
```
오타는 SDK 수정 요청 한걸까요?

2020-09-09 11:24 UTC, YuSungDuk commented on ncloud/resource_ncloud_server.go
> +		order, err := strconv.Atoi(re.FindString(*networkInterface.DeviceName))
err 처리가 안되어 있습니다.

2020-09-09 11:24 UTC, YuSungDuk commented on ncloud/resource_ncloud_server.go
> +// Delete
Delete ??

2020-09-09 11:24 UTC, YuSungDuk commented on ncloud/resource_ncloud_server.go
> +		Timeout:    DefaultTimeout,
```suggestion
		Timeout:    DefaultStopTimeout,
```

2020-09-09 11:24 UTC, YuSungDuk commented on ncloud/resource_ncloud_server_test.go
> +func TestAccResourceNcloudServer_vpc_changeSpec(t *testing.T) {
vpc 에서만 에러가 나는 군요.
```
=== RUN   TestAccResourceNcloudServer_vpc_changeSpec
--- FAIL: TestAccResourceNcloudServer_vpc_changeSpec (0.27s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1c2d635]

goroutine 6 [running]:
testing.tRunner.func1.1(0x1e6dc40, 0x2bfac80)
	/Users/user/sdk/go1.14.7/src/testing/testing.go:988 +0x30d
testing.tRunner.func1(0xc000324900)
	/Users/user/sdk/go1.14.7/src/testing/testing.go:991 +0x3f9
panic(0x1e6dc40, 0x2bfac80)
	/Users/user/sdk/go1.14.7/src/runtime/panic.go:969 +0x166
github.com/hashicorp/terraform-plugin-sdk/helper/resource.testResource(0x2021133, 0x14, 0x0, 0x0, 0x0, 0x0, 0xc0004ac7c0, 0x15, 0x0, 0x0, ...)
	/Users/user/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/resource/testing.go:978 +0x35
github.com/hashicorp/terraform-plugin-sdk/helper/resource.testStepImportState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/user/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/resource/testing_import_state.go:37 +0x1d2e
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Test(0x23531a0, 0xc000324900, 0x0, 0xc0006929a0, 0xc000694cf0, 0x0, 0x0, 0x207ca28, 0xc0000e4780, 0x3, ...)
	/Users/user/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/resource/testing.go:656 +0x827
github.com/terraform-providers/terraform-provider-ncloud/ncloud.TestAccResourceNcloudServer_vpc_changeSpec(0xc000324900)
	/Users/user/go/src/github.com/NaverCloudPlatform/terraform-provider-ncloud/ncloud/resource_ncloud_server_test.go:253 +0x6a6
testing.tRunner(0xc000324900, 0x207c360)
	/Users/user/sdk/go1.14.7/src/testing/testing.go:1039 +0xdc
created by testing.(*T).Run
	/Users/user/sdk/go1.14.7/src/testing/testing.go:1090 +0x372
FAIL	github.com/terraform-providers/terraform-provider-ncloud/ncloud	0.656s
FAIL
```

2020-09-09 11:54 UTC, sangkyu-kim commented on ncloud/resource_ncloud_server.go
> +// Delete
아 해당 주석은 CRUD 중 Delete 와 관련된 function 들이라는 의미의 주석 입니다.

2020-09-09 12:10 UTC, sangkyu-kim commented on ncloud/resource_ncloud_server.go
> +		BaseBlockStorageDiskDetailType: flattenMapByKey(r.BaseBlockStroageDiskDetailType, "code"),
아 넵 해당 model 수정 되었습니다.

2020-09-09 12:14 UTC, sangkyu-kim commented on ncloud/resource_ncloud_server_test.go
> +func TestAccResourceNcloudServer_vpc_changeSpec(t *testing.T) {
해당 오류 fix 해보려고 했는데,  Beta 의 API 상태가 불안정 한것 같습니다. 
안정화되면 확인하겠습니다.

2020-09-09 12:25 UTC, YuSungDuk commented on ncloud/resource_ncloud_server.go
> +// Delete
Update 시도 호출 되는 듯 합니다.  (updateServerInstance). 좀 더 의미를 알 수 있게 커멘트 되면 좋을 듯 합니다.

2020-09-09 12:30 UTC, sangkyu-kim commented on ncloud/resource_ncloud_server.go
> +// Delete
아 넵, collapse 해서 보면, 아래와 같이 분류하려고 한 의도였는데요. 사용자마다 보이는게 다르겠네요
![image](https://user-images.githubusercontent.com/40969251/92598316-99335e80-f2e3-11ea-9f7a-009f93c1826c.png)

커멘트는 삭제 하도록 하겠습니다.

2020-09-10 00:33 UTC, sangkyu-kim commented on ncloud/resource_ncloud_server_test.go
> +func TestAccResourceNcloudServer_vpc_changeSpec(t *testing.T) {
@YuSungDuk 다시한번 시도해봐주실수 있을까요?

```log
=== RUN   TestAccResourceNcloudServer_vpc_changeSpec
--- PASS: TestAccResourceNcloudServer_vpc_changeSpec (411.53s)
PASS

Process finished with exit code 0
```

2020-09-10 06:42 UTC, YuSungDuk approved these changes
잘 되네요 
수고 많았어요 ^^ 👍

2020-09-10 06:42 UTC, merged