#28 vpc storage
NaverCloudPlatform/terraform-provider-ncloud pull request #77
Opened 2020-09-14 10:09 UTC by sangkyu-kim

resolve #28 

#### Resources
- resource_ncloud_block_storage (Modify)

#### Data Source
- data_source_ncloud_block_storage (New)

2020-09-18 10:13 UTC, YuSungDuk requested changes

2020-09-18 10:13 UTC, YuSungDuk commented on ncloud/resource_ncloud_block_storage.go
> +	}
r == nil 이면 아래 진행되지 않아도 되지 않을가요?

2020-09-18 10:13 UTC, YuSungDuk commented on ncloud/convert_types_test.go
> +	if m[0]["cpu_count"].(float64) != 2 {
위에는 `Int32` 인데 `float64` 으로 변환되어야 할가요?

2020-09-21 02:11 UTC, sangkyu-kim commented on ncloud/convert_types_test.go
> +	if m[0]["cpu_count"].(float64) != 2 {
struct 를 map으로 변환할때 `json.Marshal` 후 `json.Unmarshal` 를 하는데, 
이 과정에서 모든 숫자가 `Float64` 형으로 변환 되어 그렇습니다.

2020-09-21 02:16 UTC, sangkyu-kim commented on ncloud/resource_ncloud_block_storage.go
> +	}
아 넵 `return nil` 추가 했습니다.

2020-09-21 02:22 UTC, YuSungDuk approved these changes
👍

2020-09-21 02:22 UTC, merged